services:
  alica:
    build:
      dockerfile: ./Dockerfile
    entrypoint: ["bash", "/entrypoint.sh"]
    environment:
      - DIGITAL=alica
    networks:
      - isolated_network
    volumes:
      - .:/digital_signature
    stdin_open: true
    tty: true

  bob:
    build:
      dockerfile: ./Dockerfile
    entrypoint: ["bash", "/entrypoint.sh"]
    environment:
      - DIGITAL=bob
    networks:
      - isolated_network
    volumes:
      - .:/digital_signature
    stdin_open: true
    tty: true

networks:
  isolated_network:
    driver: bridge